targets:
  # The targetId, must be unique.
  target_name:
    # The info fetch url like a rss-feed etc.
    fetchUrl: URL
    # The update time for the job.
    updateTime: 5
    # Set this variable to true to download over the tor-network.
    tor: false
    # Enables or disables the auto-index to a database.
    autoIndex: true
    # Defines the the index type:
    # 1 = locations
    # 2 = topics
    # 4 = content
    # meaning:
    # - 1 = locations only
    # - 3 = locations + topics
    # - 5 = location + content
    # - 6 = topic + content
    # - 7 = location + topic + content
    indexType: 7
    # Defines the extractor in the class path. Default: dev.markusk.bluelight.api.extractor.DefaultExtractor
    extractorPath: dev.markusk.bluelight.api.extractor.DefaultExtractor
    # Defines the fetcher path.
    fetcherPath: dev.markusk.bluelight.api.impl.RssFetcher
    # Defines the work-dir (the path for the downloaded articles)
    workDir: target_name/
    # Defines the suffix for the article-files
    suffix: html
    # Defines the database, when null or not set the auto-import can not work.
    database:
      # Defines which data-adapter is used for this job
      adapterName: postgres
      # Defines the connection url for the datasource.
      # Like a default sql connection string: jdbc:postgresql://HOST:PORT/DATABASE?user=USER&password=PASSWORD
      connectionUrl: CONNECTION-STRING

# A list of user-agents
userAgents:
  - Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
  - Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/1.0.154.53 Safari/525.19
  - Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) brave/0.7.10 Chrome/47.0.2526.110 Brave/0.36.5 Safari/537.36
  - Mozilla/5.0 (X11; Linux x86_64; rv:2.0b4) Gecko/20100818 Firefox/4.0b4
  - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36 OPR/32.0.1948.25
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246
  - Opera/12.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.02
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A
  - Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36