name: Build and deploy on push master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: markusk00/miner
          tags: latest
          tag_with_ref: true
          build_args: SNAPSHOT=false, BASE=master
