name: Build and deploy on push development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        with:
          fetch-depth: 0

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: markusk00/miner
          tags: development
          tag_with_sha: true
          build_args: SNAPSHOT=true, BASE=development
